spring:
  datasource:
    username: root
    password: ljfmmm666
    url: jdbc:mysql://localhost:3306/tinyblog?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info # warn
    com.example.tinyblog: debug
  file:
    path: log/blog-pro

server:
  port: 8081